### PR TITLE
Use semistandard

### LINKED ISSUE #51: Use Semistandard as Linter/Standard for Javascript

### PR DESCRIPTION
**Pull request by Denton-L**
Resolve #51

### CODE REVIEW

**Comment by DavidLu1997** [comment]
this is torture, but fine

**Comment by Denton-L** [comment]
@DavidLu1997, is this ready to merge?

**Comment by DavidLu1997** [comment]
please change makefile
https://github.com/DavidLu1997/gogogo/blob/development/webapp/Makefile

**Comment by DavidLu1997** [comment]
+1 :+1:

**Pull request merged**
